name: Build and Publish

on: [workflow_dispatch]

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: https://github.com/the78mole/esphome_components/blob/main/components/km271_wifi/km271-for-friends.yaml
      name: KM271-WiFi
